version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/showcasify
      - ENVIRONMENT=docker
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - showcasify-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - showcasify-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=showcasify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - showcasify-network

volumes:
  postgres_data:

networks:
  showcasify-network:
    driver: bridge 